# Generated by Django 4.2.4 on 2023-09-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irctcBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.CharField(max_length=100, unique=True)),
                ('source', models.CharField(max_length=50, unique=True)),
                ('destination', models.CharField(max_length=50, unique=True)),
                ('seat_capacity', models.IntegerField()),
                ('arrival_time_at_source', models.CharField(max_length=8)),
                ('arrival_time_at_destination', models.CharField(max_length=8)),
            ],
        ),
    ]
